name: Bug Report
description: Report a bug or issue with ScentPlanet
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: input
    id: version
    attributes:
      label: ScentPlanet Version
      description: What version of ScentPlanet are you using? (Found in Settings > About)
      placeholder: e.g., 0.3.3
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows 11
        - Windows 10
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs (if applicable)
      description: |
        If applicable, paste any error logs here.
        You can find logs in: `%APPDATA%\com.scentplanet.dev\logs`
      render: shell

  - type: input
    id: game
    attributes:
      label: Game Being Played (if applicable)
      description: Which game were you playing when this occurred?
      placeholder: e.g., Red Dead Redemption 2

  - type: checkboxes
    id: hardware
    attributes:
      label: Hardware Status
      options:
        - label: Scent device was connected when this occurred
        - label: This issue occurs without the scent device connected

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or screen recordings here.
