name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your input in making ScentPlanet better.

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What area of ScentPlanet does this relate to?
      options:
        - Game Support (new game)
        - Scene Recognition
        - Hardware / BLE
        - User Interface
        - Settings / Configuration
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: checkboxes
    id: willingness
    attributes:
      label: Contribution
      description: Would you be willing to help with this feature?
      options:
        - label: I would be willing to contribute a game profile for this feature
        - label: I would be willing to help test this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots here.
